Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/stud-lscholz/RLdelay/rlrd/rlrd/__main__.py", line 28, in <module>
    raise AttributeError("Undefined command: " + cmd)
AttributeError: Undefined command: run_fs
